"""ComfyUI nodes that host iZotope Ozone VST3 plugins via pedalboard."""

from __future__ import annotations

import json
import math
import os
import re
import uuid
import wave as pywave

import numpy as np
import torch
from PIL import Image, ImageDraw, ImageFont
from typing_extensions import override

from comfy_api.latest import ComfyExtension, IO

from .ozone_engine import (
    DEFAULT_VST_DIR,
    _apply_global_preset,
    discover_global_presets,
    discover_presets,
    list_ozone_plugins,
    parameter_names,
    parameter_values,
    process as engine_process,
)


def _default_plugins() -> list[str]:
    plugins = list_ozone_plugins()
    return plugins or ["Ozone 12.vst3"]


def _default_plugin(plugins: list[str]) -> str:
    return "Ozone 12.vst3" if "Ozone 12.vst3" in plugins else plugins[0]


def _parse_params(params_json: str) -> tuple[dict, list[str]]:
    try:
        data = json.loads(params_json or "{}")
    except json.JSONDecodeError as e:
        return {}, [f"params_json is not valid JSON, ignored: {e}"]
    if not isinstance(data, dict):
        return {}, ["params_json must be a JSON object, ignored"]
    return data, []


def _json_safe(value):
    """Make values JSON-serializable (numpy scalars, etc.)."""
    if isinstance(value, np.generic):
        return value.item()
    return value


def _json_safe_value(value):
    """Recursively coerce a parameter value into a JSON-serializable form.

    Some plugin parameters expose non-scalar objects; fall back to str().
    """
    if value is None or isinstance(value, (bool, int, float, str)):
        return value
    if isinstance(value, np.generic):
        return value.item()
    try:
        if isinstance(value, (list, tuple)):
            return [_json_safe_value(v) for v in value]
        if isinstance(value, dict):
            return {k: _json_safe_value(v) for k, v in value.items()}
        return str(value)
    except Exception:  # noqa: BLE001 - never fail node execution over a value
        return str(value)


# ---------------------------------------------------------------------------
# Widget-based per-module nodes, built from param_cache.json metadata.
# ---------------------------------------------------------------------------

PARAM_CACHE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "param_cache.json")
MAX_WIDGETS = 48

_PARAM_CACHE: dict | None = None


def _load_param_cache() -> dict:
    """Load param_cache.json (generated by generate_param_cache.py)."""
    global _PARAM_CACHE
    if _PARAM_CACHE is None:
        try:
            with open(PARAM_CACHE_PATH, encoding="utf-8") as f:
                _PARAM_CACHE = json.load(f)
        except Exception:  # noqa: BLE001 - missing cache = no widget nodes
            _PARAM_CACHE = {}
    return _PARAM_CACHE


def _finite(value) -> bool:
    """True for finite numbers (JSON-safe; browser JSON.parse rejects NaN/Infinity)."""
    return isinstance(value, (int, float)) and math.isfinite(value)


def _prettify(name: str) -> str:
    """Turn a python param name into a readable label."""
    label = name.replace("_unlocked", "").replace("_", " ").strip().title()
    return label or name


# Headless caveats per module, shown in the node description. Verified on
# this machine with the real plugins (see README for the details).
_MODULE_NOTES = {
    "Ozone 12 Equalizer.vst3": (
        "Note: the Equalizer bands do not respond in headless mode (iZotope "
        "VST3 quirk) - only the input/output gains work. Use Ozone 12 Vintage EQ "
        "(fixed bands, verified) or Ozone 12 Dynamic EQ (band frequency stuck "
        "low, gain applies) for EQ processing."
    ),
    "Ozone 12 Dynamic EQ.vst3": (
        "Note: band gains apply, but the band frequency control does not move "
        "the band in headless mode (iZotope VST3 quirk) - the boost lands at the "
        "band's default position. Use Ozone 12 Vintage EQ for a targeted "
        "high/mid boost."
    ),
    "Ozone 12 Stem EQ.vst3": (
        "Note: Stem EQ needs its stem analysis to run; without it the per-stem "
        "gains have no audible effect."
    ),
    "Ozone 12 Unlimiter.vst3": (
        "Note: works headless when the Amount is raised (the Amount defaults "
        "to 0, which is why a preset alone seems inert). Verified: threshold "
        "-20 + amount 100 on pre-limited material -> +3.8 dB RMS. Needs "
        "over-limited/clipped input to have something to recover."
    ),
    "Ozone 12 Vintage Compressor.vst3": (
        "Note: works headless (verified: threshold -40 + ratio 8 -> -11 dB "
        "RMS; add attack/release for the full sound). The default ratio is "
        "~1.5:1 so threshold alone barely compresses - raise the Ratio."
    ),
    "Ozone 12 Vintage Tape.vst3": (
        "Note: works headless when Harmonics/Bias are raised (verified: "
        "drive 10 + harmonics 100 + bias 100 -> -8.3 dB RMS saturation). "
        "Drive alone (harmonics at 0) is subtle."
    ),
    "Ozone 12 Maximizer.vst3": (
        "Note: the limiter Threshold is NOT exposed by the VST3 (verified even "
        "in the full Ozone 12.vst3, 873 params), so it stays at its default "
        "(~0 dBFS) and only clips true overs: on normal music below 0 dBFS the "
        "module is inaudible. What works: input/output gain, and Soft Clip "
        "(On + Mix) which is very audible. For real limiting use Ozone 12 "
        "Vintage Limiter (its Threshold is exposed and verified to work, "
        "presets apply ~3/3)."
    ),
    "Ozone 12 Impact.vst3": (
        "Note: the band Amount sliders do process (verified: all bands at 100 "
        "raises RMS ~ +6.7 dB and changes the transient character). Most Impact "
        "presets map poorly because the crossover cutoffs and per-band "
        "bypass/active flags are not exposed by the VST3 (e.g. 'EDM Snare Body' "
        "applies only band 2 amount). Presets that map 100% and are verified to "
        "work: 'Hype It Up' (RMS +4.1 dB) and 'Chill It Out' (RMS -1.2 dB). "
        "Otherwise set the band Amounts manually."
    ),
}


# Control priority within a band chain, so the 48-widget cap keeps the most
# useful/audible controls (enable, frequency, gain...) instead of filling up
# with attack/release/auto settings.
_PARAM_KIND_PRIORITY = {
    "enable": 0,
    "frequency": 1,
    "gain": 2,
    "threshold": 3,
    "q": 4,
    "shape": 5,
    "phase": 6,
    "offset": 7,
    "attack": 8,
    "release": 9,
    "auto": 10,
    "mix": 11,
    "amount": 12,
}


def _param_kind_rank(name: str) -> int:
    for kind, prio in _PARAM_KIND_PRIORITY.items():
        if kind in name:
            return prio
    return 99


def _filter_widget_params(metas: list[dict]) -> list[dict]:
    """Pick the params that become node widgets (max MAX_WIDGETS).

    Ozone exposes each band chain twice (stereo_main + aux) and many gain
    knobs twice (locked/unlocked). We drop the locked duplicates and then
    prioritize: global gains first, then the audible stereo_main chain (and
    any non-aux param), and the aux chain last. Within a chain the most
    audible controls (enable, frequency, gain, threshold, Q...) come before
    attack/release/auto. Plain alphabetical selection would pick the aux
    chain and fill the cap with attack/auto params, hiding the controls that
    actually drive the sound.
    """
    picked = [m for m in metas if not m.get("locked_dup")]

    def rank(m: dict) -> tuple:
        name = m["name"]
        if name.startswith("gain_") or name == "global_bypass":
            return (0, 0, 0, name)
        if "_aux_" not in name:
            return (1, 0, _param_kind_rank(name), name)
        return (2, 0, _param_kind_rank(name), name)

    picked.sort(key=rank)
    return picked[:MAX_WIDGETS]


def _changed_widget_params(specs: list[dict], widgets: dict) -> dict:
    """Keep only the widget values the user actually changed.

    The engine applies a preset first, then the widget params. Sending every
    widget value (including untouched defaults) would silently reset the
    preset's settings back to the defaults. So we drop values that still
    equal their cached default: the preset keeps its effect, and explicit
    slider/toggle changes still override it.
    """
    params = {}
    for m in specs:
        name = m["name"]
        if name not in widgets:
            continue
        default = m.get("default")
        value = widgets[name]
        try:
            if m.get("bool"):
                unchanged = bool(value) == bool(default)
            elif m.get("choice"):
                unchanged = str(value) == str(default)
            else:
                unchanged = float(value) == float(default)
        except (TypeError, ValueError):
            unchanged = False
        if not unchanged:
            params[name] = value
    return params


def _make_module_node(plugin_filename: str, metas: list[dict]):
    """Create a ComfyUI node class exposing the module's parameters as widgets."""
    params = _filter_widget_params(metas)

    class OzoneModuleNode(IO.ComfyNode):
        PLUGIN_FILE = plugin_filename
        PARAM_SPECS = params

        @classmethod
        def define_schema(cls):
            inputs = [IO.Audio.Input("audio", tooltip="Audio to process.")]
            for m in cls.PARAM_SPECS:
                label = _prettify(m["name"])
                unit = m.get("unit") or ""
                if m["bool"]:
                    inputs.append(
                        IO.Boolean.Input(
                            m["name"],
                            display_name=label,
                            default=bool(m.get("default", False)),
                            tooltip=f"{label} (on/off)",
                        )
                    )
                elif m.get("choice"):
                    choices = list(m.get("choices") or [])
                    default = m.get("default")
                    if default not in choices:
                        default = choices[0] if choices else ""
                    inputs.append(
                        IO.Combo.Input(
                            m["name"],
                            display_name=label,
                            options=choices,
                            default=default,
                            tooltip=f"{label} (choice)",
                        )
                    )
                else:
                    # Only pass finite, well-ordered ranges: non-finite values
                    # would produce invalid JSON for the frontend, and min >= max
                    # breaks the slider.
                    kwargs = {"default": 0.0}
                    if _finite(m.get("default")):
                        kwargs["default"] = float(m["default"])
                    if (
                        _finite(m.get("min"))
                        and _finite(m.get("max"))
                        and m["max"] > m["min"]
                    ):
                        kwargs["min"] = float(m["min"])
                        kwargs["max"] = float(m["max"])
                    if _finite(m.get("step")) and m["step"] > 0:
                        kwargs["step"] = float(m["step"])
                    if "min" in kwargs and "max" in kwargs:
                        kwargs["default"] = max(
                            kwargs["min"], min(kwargs["max"], kwargs["default"])
                        )
                    inputs.append(
                        IO.Float.Input(
                            m["name"],
                            display_name=label,
                            tooltip=f"{label} [{unit}]" if unit else label,
                            **kwargs,
                        )
                    )
            presets = [p["name"] for p in discover_presets(cls.PLUGIN_FILE)]
            inputs.append(
                IO.Combo.Input(
                    "preset",
                    options=[""] + presets,
                    default="",
                    tooltip=(
                        "Ozone preset to apply (factory and user presets found on "
                        "this machine). Values are applied best-effort; unmappable "
                        "parameters are reported in the info output. Needs 'Preset On' "
                        "to take over."
                    ),
                )
            )
            inputs.append(
                IO.Boolean.Input(
                    "preset_enabled",
                    display_name="Preset On",
                    default=False,
                    tooltip=(
                        "ON: the selected preset takes over (manual settings are "
                        "ignored). OFF: manual settings apply and the preset is "
                        "ignored."
                    ),
                )
            )
            inputs.append(
                IO.String.Input(
                    "preset_path",
                    default="",
                    advanced=True,
                    tooltip="Optional path to a raw VST3 state file (.vstpreset) or iZotope .xml preset.",
                )
            )
            inputs.append(
                IO.String.Input(
                    "vst_dir",
                    default=DEFAULT_VST_DIR,
                    advanced=True,
                    tooltip="Folder containing the .vst3 files.",
                )
            )
            module_label = plugin_filename.replace(".vst3", "").replace("Ozone 12 ", "")
            note = _MODULE_NOTES.get(plugin_filename, "")
            description = (
                f"Applies the {plugin_filename} Ozone module with real parameter "
                "widgets (sliders and toggles)."
            )
            if note:
                description += f" {note}"
            return IO.Schema(
                node_id=cls.NODE_ID,
                display_name=f"Ozone 12 {module_label}",
                category="audio/vst/ozone",
                description=description,
                inputs=inputs,
                outputs=[
                    IO.Audio.Output("audio", tooltip="Processed audio."),
                    IO.String.Output("info", tooltip="JSON summary of the processing run."),
                ],
            )

        @classmethod
        def execute(
            cls, audio, preset, preset_path, vst_dir, preset_enabled=False, **widgets
        ) -> IO.NodeOutput:
            if audio is None:
                raise ValueError(f"{cls.NODE_ID}: input audio is None")
            preset_file = None
            if preset:
                for p in discover_presets(cls.PLUGIN_FILE):
                    if p["name"] == preset:
                        preset_file = p["path"]
                        break
            preset_file = preset_file or preset_path or None
            params = _changed_widget_params(cls.PARAM_SPECS, widgets)
            if preset_enabled:
                if preset_file:
                    # Preset takes over: manual settings are ignored.
                    params = {}
                # else: preset requested but none selected -> manual fallback.
            else:
                # Manual mode: the preset is ignored entirely.
                preset_file = None
            waveform = audio["waveform"].float().cpu()
            sample_rate = int(audio["sample_rate"])
            outputs = []
            infos = []
            for i in range(waveform.shape[0]):
                y, info = engine_process(
                    waveform[i].numpy(),
                    sample_rate,
                    cls.PLUGIN_FILE,
                    vst_dir=vst_dir,
                    preset_path=preset_file,
                    params=params,
                )
                outputs.append(torch.from_numpy(y))
                infos.append(info)
            summary = {
                "plugin": cls.PLUGIN_FILE,
                "sample_rate": sample_rate,
                "runs": infos,
                "warnings": [w for info in infos for w in info["warnings"]],
            }
            return IO.NodeOutput(
                {"waveform": torch.stack(outputs, dim=0), "sample_rate": sample_rate},
                json.dumps(summary, default=_json_safe, indent=1),
            )

    key = (
        plugin_filename.replace("Ozone 12 ", "")
        .replace(".vst3", "")
        .replace(" ", "")
        .replace("-", "")
    )
    OzoneModuleNode.NODE_ID = f"OzoneVST{key}"
    OzoneModuleNode.__name__ = f"OzoneVST{key}"
    return OzoneModuleNode


def _build_module_nodes() -> list[type[IO.ComfyNode]]:
    nodes = []
    for filename, metas in _load_param_cache().items():
        try:
            nodes.append(_make_module_node(filename, metas))
        except Exception as e:  # noqa: BLE001 - one bad module shouldn't kill startup
            print(f"[ComfyUI-Ozone12] failed to build node for {filename}: {e}")
    return nodes


_MODULE_NODES = _build_module_nodes()


PRESET_TYPES_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "preset_types.json"
)

_PRESET_TYPES: dict | None = None


def _load_preset_types() -> dict:
    """Classification of each global preset (measured: loud/tonal/dynamic)."""
    global _PRESET_TYPES
    if _PRESET_TYPES is None:
        try:
            with open(PRESET_TYPES_PATH, encoding="utf-8") as f:
                _PRESET_TYPES = json.load(f)
        except Exception:  # noqa: BLE001 - measurements are optional
            _PRESET_TYPES = {}
    return _PRESET_TYPES


_TYPE_BADGE = {
    "loud": "[VOL]",
    "tonal": "[TONE]",
    "dynamic": "[DYN]",
    "full": "[FULL]",
    "subtle": "[SUB]",
}


def _preset_label(name: str, measurement: dict | None) -> str:
    """Dropdown label: 'CD Master [VOL -3.9dB]' or 'CD Master' if unknown."""
    if not measurement:
        return name
    badge = _TYPE_BADGE.get(measurement.get("type", ""), "")
    rms = measurement.get("rms")
    suffix = f" {badge}" if badge else ""
    if isinstance(rms, (int, float)):
        suffix += f" {rms:+.1f}dB"
    return f"{name}{suffix}"


_BADGE_RE = re.compile(r" \[(VOL|TONE|DYN|FULL|SUB)\] [+-]?[0-9.]+dB$")


def _preset_name_from_label(label: str) -> str:
    """Strip the measured badge suffix back to the real preset name."""
    return _BADGE_RE.sub("", label)


def _modules_view(info: dict) -> dict:
    """Compact per-module view for the frontend widget (badges).

    Keeps only what the node UI needs: which sections were active, how many
    params were applied and the measured effect (Δ RMS / Δ crest in dB).
    """
    modules = []
    for m in info.get("modules", []):
        modules.append(
            {
                "section": m.get("section"),
                "enabled": bool(m.get("enabled")),
                "params": len(m.get("params_applied", [])),
                "rms": m.get("effect_rms_db"),
                "crest": m.get("effect_crest_db"),
            }
        )
    return {"preset": info.get("preset"), "modules": modules}


class OzoneGlobalMastering(IO.ComfyNode):
    """Applies a full mastering-chain (global) Ozone preset."""

    @classmethod
    def define_schema(cls):
        presets = discover_global_presets()
        types = _load_preset_types()
        return IO.Schema(
            node_id="OzoneGlobalMastering",
            display_name="Ozone Global Mastering",
            category="audio/vst/ozone",
            description=(
                "Applies a complete Ozone mastering preset (the global presets "
                "from Ozone's Preset Manager: All Purpose Mastering, Expert "
                "Curated Presets, Genre-Specific Mastering, Mix Bus, Ozone "
                "Legacy, Stem Focus). Each enabled module of the preset is "
                "applied through its standalone plugin, chained in master "
                "order (EQ -> dynamics -> limiter). The full Ozone 12.vst3 "
                "cannot host the chain headlessly (its rack state is not "
                "exposed), so each module runs through its standalone plugin. "
                "Nearly all modules process (only the Equalizer bands and Stem "
                "EQ are inert headless).\n\n"
                "Preset badges (measured on a reference signal): [VOL] = main "
                "effect is loudness, [TONE] = tonal change, [DYN] = dynamics "
                "/transients, [FULL] = both volume and tone. The number is "
                "the RMS change in dB."
            ),
            inputs=[
                IO.Audio.Input("audio", tooltip="Audio to master."),
                IO.Combo.Input(
                    "preset",
                    options=[
                        _preset_label(p["name"], types.get(p["name"])) for p in presets
                    ],
                    default=_preset_label(presets[0]["name"], types.get(presets[0]["name"])) if presets else "",
                    tooltip=(
                        "Full-chain Ozone preset (global presets folder). "
                        "Badges: [VOL] loudness, [TONE] tonal, [DYN] dynamics, "
                        "[FULL] both, then the measured RMS change in dB. "
                        "Enabled modules are chained through their standalone "
                        "plugins."
                    ),
                ),
                IO.Boolean.Input(
                    "preset_enabled",
                    display_name="Preset On",
                    default=True,
                    tooltip="OFF: the audio passes through unchanged.",
                ),
                IO.Float.Input(
                    "amount",
                    display_name="Amount",
                    default=100.0,
                    min=0.0,
                    max=100.0,
                    step=1.0,
                    tooltip=(
                        "How much of the mastered (wet) signal to mix in, 0-100%. "
                        "100% = full preset, 0% = dry. A parallel mix of the dry "
                        "and processed audio (the chain is latency-free, so the "
                        "mix is phase-clean)."
                    ),
                ),
                IO.String.Input(
                    "vst_dir",
                    default=DEFAULT_VST_DIR,
                    advanced=True,
                    tooltip="Folder containing the .vst3 files.",
                ),
            ],
            outputs=[
                IO.Audio.Output("audio", tooltip="Mastered audio."),
                IO.String.Output("info", tooltip="JSON summary (modules applied, warnings)."),
            ],
        )

    @classmethod
    def execute(cls, audio, preset, preset_enabled, amount, vst_dir) -> IO.NodeOutput:
        if audio is None:
            raise ValueError("OzoneGlobalMastering: input audio is None")
        waveform = audio["waveform"].float().cpu().numpy()
        sample_rate = int(audio["sample_rate"])
        amount = float(amount)
        if not preset_enabled or not preset or amount <= 0.0:
            summary = {
                "preset": preset if preset_enabled else None,
                "amount": amount,
                "bypassed": True,
                "warnings": [],
            }
            ui = {"ozone_modules": [{"preset": preset if preset_enabled else None, "bypassed": True, "modules": []}]}
            return IO.NodeOutput(audio, json.dumps(summary), ui=ui)
        preset_name = _preset_name_from_label(preset)
        preset_path = next(
            (p["path"] for p in discover_global_presets() if p["name"] == preset_name), None
        )
        if preset_path is None:
            raise ValueError(f"OzoneGlobalMastering: preset not found: {preset}")
        preset = preset_name
        outputs = []
        infos = []
        dry = waveform.astype(np.float32)
        for i in range(dry.shape[0]):
            y, info = _apply_global_preset(
                dry[i], sample_rate, preset_path, vst_dir=vst_dir
            )
            wet = y.astype(np.float32)
            if amount < 100.0:
                # Parallel mix. The chain measured 0 samples of latency, so
                # a linear crossfade is phase-clean. Guard length just in
                # case a module ever pads/truncates.
                n = min(dry[i].shape[-1], wet.shape[-1])
                w = amount / 100.0
                mixed = (1.0 - w) * dry[i][..., :n] + w * wet[..., :n]
                y = mixed
            outputs.append(torch.from_numpy(y))
            infos.append(info)
        summary = {
            "preset": preset,
            "amount": amount,
            "sample_rate": sample_rate,
            "runs": infos,
            "warnings": [w for info in infos for w in info["warnings"]],
        }
        ui = {"ozone_modules": [_modules_view(info) for info in infos]}
        return IO.NodeOutput(
            {"waveform": torch.stack(outputs, dim=0), "sample_rate": sample_rate},
            json.dumps(summary, default=_json_safe, indent=1),
            ui=ui,
        )


class OzoneVST(IO.ComfyNode):
    """Applies an iZotope Ozone VST3 plugin to the input audio."""

    @classmethod
    def define_schema(cls):
        plugins = _default_plugins()
        return IO.Schema(
            node_id="OzoneVST",
            display_name="Ozone VST Processor",
            category="audio/vst",
            description=(
                "Hosts an iZotope Ozone VST3 plugin headlessly (via pedalboard) and applies "
                "it to the input audio. The plugin must be authorized on this machine "
                "(iZotope Product Portal / iLok). Use 'Ozone VST Parameter Inspector' to "
                "discover parameter names for params_json."
            ),
            inputs=[
                IO.Audio.Input("audio", tooltip="Audio to process."),
                IO.Combo.Input(
                    "plugin",
                    options=plugins,
                    default=_default_plugin(plugins),
                    tooltip="VST3 file to load from vst_dir (editable: type any .vst3 filename).",
                ),
                IO.String.Input(
                    "vst_dir",
                    default=DEFAULT_VST_DIR,
                    advanced=True,
                    tooltip="Folder containing the .vst3 files.",
                ),
                IO.String.Input(
                    "preset_path",
                    default="",
                    tooltip="Optional path to a preset file (.vstpreset / Ozone preset).",
                ),
                IO.String.Input(
                    "params_json",
                    default="{}",
                    multiline=True,
                    tooltip='Parameter overrides as JSON, e.g. {"maximizer_threshold_db": -12.0}.',
                ),
            ],
            outputs=[
                IO.Audio.Output(
                    "audio",
                    tooltip="Processed audio (same sample rate / channel count as the input).",
                ),
                IO.String.Output("info", tooltip="JSON summary of the processing run."),
            ],
        )

    @classmethod
    def execute(cls, audio, plugin, vst_dir, preset_path, params_json) -> IO.NodeOutput:
        if audio is None:
            raise ValueError("OzoneVST: input audio is None")
        params, warnings = _parse_params(params_json)

        waveform = audio["waveform"].float().cpu()
        sample_rate = int(audio["sample_rate"])

        outputs = []
        infos = []
        for i in range(waveform.shape[0]):
            x = waveform[i].numpy()
            y, info = engine_process(
                x,
                sample_rate,
                plugin,
                vst_dir=vst_dir,
                preset_path=preset_path or None,
                params=params,
            )
            outputs.append(torch.from_numpy(y))
            infos.append(info)

        out_waveform = torch.stack(outputs, dim=0)
        summary = {
            "plugin": plugin,
            "sample_rate": sample_rate,
            "runs": infos,
            "warnings": warnings + [w for info in infos for w in info["warnings"]],
        }
        return IO.NodeOutput(
            {"waveform": out_waveform, "sample_rate": sample_rate},
            json.dumps(summary, default=_json_safe, indent=1),
        )


class OzoneVSTParams(IO.ComfyNode):
    """Lists the parameters exposed by an Ozone VST3 plugin."""

    @classmethod
    def define_schema(cls):
        plugins = _default_plugins()
        return IO.Schema(
            node_id="OzoneVSTParams",
            display_name="Ozone VST Parameter Inspector",
            category="audio/vst",
            description=(
                "Lists the parameters of an Ozone VST3 plugin (python-safe names and current "
                "values) so you can build params_json for 'Ozone VST Processor'."
            ),
            inputs=[
                IO.Combo.Input(
                    "plugin",
                    options=plugins,
                    default=_default_plugin(plugins),
                    tooltip="VST3 file to inspect.",
                ),
                IO.String.Input(
                    "vst_dir",
                    default=DEFAULT_VST_DIR,
                    advanced=True,
                    tooltip="Folder containing the .vst3 files.",
                ),
            ],
            outputs=[
                IO.String.Output(
                    "params_json",
                    tooltip="All parameters with their current values, as JSON.",
                ),
                IO.String.Output("param_names", tooltip="One parameter name per line."),
            ],
        )

    @classmethod
    def execute(cls, plugin, vst_dir) -> IO.NodeOutput:
        names = parameter_names(plugin, vst_dir)
        values = parameter_values(plugin, vst_dir)
        safe = {name: _json_safe_value(value) for name, value in values.items()}
        return IO.NodeOutput(
            json.dumps(safe, indent=1),
            "\n".join(names),
        )


def _save_temp_wav(audio: dict, prefix: str) -> dict:
    """Write the audio to a temp WAV file for the frontend player.

    Returns the ComfyUI file reference {filename, subfolder, type}.
    """
    import folder_paths

    waveform = audio["waveform"].float().cpu().numpy()  # [B, C, S]
    sr = int(audio["sample_rate"])
    wav = waveform[0]
    if wav.ndim != 2:
        wav = wav.reshape(1, -1)
    channels = wav.shape[0]
    samples = np.clip(np.round(wav * 32767.0), -32768, 32767).astype(np.int16)
    interleaved = samples.T.reshape(-1) if channels > 1 else samples[0]
    temp_dir = folder_paths.get_temp_directory()
    os.makedirs(temp_dir, exist_ok=True)
    filename = f"{prefix}_{uuid.uuid4().hex[:8]}.wav"
    path = os.path.join(temp_dir, filename)
    with pywave.open(path, "wb") as f:
        f.setnchannels(channels)
        f.setsampwidth(2)
        f.setframerate(sr)
        f.writeframes(interleaved.tobytes())
    return {"filename": filename, "subfolder": "", "type": "temp"}


def _db_fs(value: float) -> float:
    """Linear amplitude -> dBFS, floored."""
    if value <= 1e-9:
        return -120.0
    return 20.0 * math.log10(value)


def _level_color(db: float) -> tuple[int, int, int]:
    """Green / yellow / red depending on the level."""
    if db < -18:
        return (64, 224, 96)
    if db < -6:
        return (240, 224, 64)
    return (240, 80, 80)


def _render_level_meter(wav: np.ndarray, mode: str, bars: int, meter_h: int, sample_rate: int):
    """Render a peak/RMS history meter. Returns (HWC float32 0..1 image, summary str)."""
    channels = min(wav.shape[0], 2)
    left, right, top, bottom = 46, 14, 20, 28
    gap = 28
    bar_w, gap_w = 5, 1
    width = left + bars * (bar_w + gap_w) + right
    height = top + channels * (meter_h + gap) + bottom
    img = Image.new("RGB", (width, height), (26, 28, 32))
    d = ImageDraw.Draw(img)
    try:
        font = ImageFont.load_default(size=13)
    except TypeError:  # older Pillow
        font = ImageFont.load_default()

    show_peak = mode in ("Peak", "Peak & RMS")
    show_rms = mode in ("RMS", "Peak & RMS")

    summaries = []
    for c in range(channels):
        base_y = top + c * (meter_h + gap)
        label = ("L", "R")[c] if channels == 2 else "M"
        d.text((6, base_y + 2), label, fill=(220, 220, 220), font=font)

        # Gridlines + dB labels
        for db in (-60, -48, -36, -24, -12, 0):
            frac = (db + 60.0) / 60.0
            y = base_y + meter_h - frac * meter_h
            d.line([(left, y), (width - right, y)], fill=(52, 56, 62))
            d.text((left - 34, y - 8), f"{db}", fill=(170, 170, 170), font=font)

        chunk = max(1, wav.shape[1] // bars)
        peak_hold = 0.0
        track_peak = 0.0
        track_rms = 0.0
        for i in range(bars):
            seg = wav[c, i * chunk : (i + 1) * chunk]
            rms = float(np.sqrt(np.mean(np.square(seg)))) if seg.size else 0.0
            peak = float(np.max(np.abs(seg))) if seg.size else 0.0
            track_peak = max(track_peak, peak)
            track_rms = max(track_rms, rms)
            peak_hold = max(peak_hold, peak)
            x0 = left + i * (bar_w + gap_w)
            if show_rms:
                frac = max(0.0, min(1.0, (_db_fs(rms) + 60.0) / 60.0))
                bar_h = max(1, int(frac * (meter_h - 6)))
                d.rectangle(
                    [x0, base_y + meter_h - bar_h - 3, x0 + bar_w, base_y + meter_h - 3],
                    fill=_level_color(_db_fs(rms)),
                )
            if show_peak:
                frac = max(0.0, min(1.0, (_db_fs(peak) + 60.0) / 60.0))
                py = base_y + meter_h - int(frac * (meter_h - 6)) - 5
                d.rectangle([x0, py, x0 + bar_w, py + 2], fill=(255, 255, 255))
        # Peak-hold line
        hold_frac = max(0.0, min(1.0, (_db_fs(peak_hold) + 60.0) / 60.0))
        hold_y = base_y + meter_h - hold_frac * meter_h
        d.line([(left, hold_y), (width - right, hold_y)], fill=(255, 130, 130), width=1)

        summaries.append(
            f"{label} | Peak: {_db_fs(track_peak):.1f} dB | RMS: {_db_fs(track_rms):.1f} dB"
        )

    arr = np.asarray(img, dtype=np.float32) / 255.0  # HWC 0..1
    return arr, " | ".join(summaries)


class OzoneLevelMeter(IO.ComfyNode):
    """Renders a peak/RMS level meter of the audio as an image."""

    @classmethod
    def define_schema(cls):
        return IO.Schema(
            node_id="OzoneLevelMeter",
            display_name="Ozone Level Meter",
            category="audio/vst/ozone",
            description=(
                "Renders a level meter (peak/RMS history per channel) of the audio as an "
                "image and passes the audio through unchanged. Wire the image to "
                "Preview Image."
            ),
            inputs=[
                IO.Audio.Input("audio", tooltip="Audio to visualize."),
                IO.Combo.Input(
                    "mode",
                    options=["Peak & RMS", "Peak", "RMS"],
                    default="Peak & RMS",
                    tooltip="Which level to draw.",
                ),
                IO.Int.Input(
                    "bars",
                    default=120,
                    min=16,
                    max=512,
                    tooltip="Number of time chunks (bars) to draw.",
                ),
                IO.Int.Input(
                    "height",
                    default=140,
                    min=60,
                    max=400,
                    advanced=True,
                    tooltip="Height of each channel meter in pixels.",
                ),
            ],
            outputs=[
                IO.Image.Output(
                    "visualization", tooltip="Level meter image. Wire to Preview Image."
                ),
                IO.Audio.Output("audio", tooltip="Input audio passed through unchanged."),
                IO.String.Output("levels", tooltip="Peak/RMS levels per channel in dBFS."),
            ],
        )

    @classmethod
    def execute(cls, audio, mode, bars, height) -> IO.NodeOutput:
        if audio is None:
            raise ValueError("OzoneLevelMeter: input audio is None")
        waveform = audio["waveform"].float().cpu().numpy()  # [B, C, S]
        images = []
        summaries = []
        sample_rate = int(audio["sample_rate"])
        for wav in waveform:
            arr, summary = _render_level_meter(wav, mode, int(bars), int(height), sample_rate)
            images.append(torch.from_numpy(arr))
            summaries.append(summary)
        # Note: ComfyUI's executor expects each ui value to be a *list* of
        # entries (one per execution); a bare dict would be iterated by key.
        ui = {
            "ozone_meter": [
                {
                    "file": _save_temp_wav(audio, "ozone_meter"),
                    "sample_rate": sample_rate,
                    "duration": round(waveform.shape[-1] / sample_rate, 3),
                }
            ]
        }
        return IO.NodeOutput(torch.stack(images, dim=0), audio, "\n".join(summaries), ui=ui)


class OzoneABCompare(IO.ComfyNode):
    """A/B compare: player with two tracks switched from the node widget."""

    @classmethod
    def define_schema(cls):
        return IO.Schema(
            node_id="OzoneABCompare",
            display_name="Ozone A/B Compare",
            category="audio/vst/ozone",
            description=(
                "Loads two audios into the embedded player and lets you switch between "
                "track A and track B at any moment, even during playback (Track A / "
                "Track B buttons in the node). The audio output is track A (or B if "
                "A is not connected)."
            ),
            inputs=[
                IO.Audio.Input("audio_a", tooltip="Track A (e.g. dry audio)."),
                IO.Audio.Input("audio_b", tooltip="Track B (e.g. processed audio)."),
            ],
            outputs=[
                IO.Audio.Output(
                    "audio", tooltip="Track A (or track B if A is not connected)."
                ),
                IO.String.Output("info", tooltip="Which track is being output."),
            ],
        )

    @classmethod
    def execute(cls, audio_a, audio_b) -> IO.NodeOutput:
        if audio_a is None and audio_b is None:
            raise ValueError("OzoneABCompare: both inputs are None")
        chosen, label = (audio_a, "A") if audio_a is not None else (audio_b, "B")
        info = f"Output: track {label} (switch A/B in the node's player)"
        ui = {
            "ozone_ab": [
                {
                    "a": _save_temp_wav(audio_a, "ozone_ab_a") if audio_a is not None else None,
                    "b": _save_temp_wav(audio_b, "ozone_ab_b") if audio_b is not None else None,
                }
            ]
        }
        return IO.NodeOutput(chosen, info, ui=ui)


class OzoneExtension(ComfyExtension):
    @override
    async def get_node_list(self) -> list[type[IO.ComfyNode]]:
        return [
            OzoneVST,
            OzoneVSTParams,
            OzoneLevelMeter,
            OzoneABCompare,
            OzoneGlobalMastering,
            *_MODULE_NODES,
        ]


async def comfy_entrypoint() -> OzoneExtension:
    return OzoneExtension()
